apiVersion: v1
kind: Service
metadata:
  name: recfacial-legado-postgres-port
spec:
  type: NodePort
  selector:
    app: recfacial-legado-postgres
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 31001