apiVersion: v1
kind: Service
metadata:
  labels:
    app: recfacial-legado-postgres
  name: recfacial-legado-postgres
spec:
  ports:
    - name: 5432-tcp
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: recfacial-legado-postgres
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}